src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>json__c</fullName>
        <label>json</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/Clustering_Run__c.object
<CustomObject>
    <description>This object represents a run of the K-Means clustering algorithm with a series of associated iteration records.</description>
    <fields>
        <fullName>Dimensions__c</fullName>
        <label>Dimensions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initial_Number_of_Clusters__c</fullName>
        <description>The number of clusters that we initially want to work with - note that at the end of our algorithm this may have reduced to a smaller number.</description>
        <label>Number of Clusters</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Value__c</fullName>
        <label>Max Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Clustering Run</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>Clustering Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clustering Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Iteration__c.object
<CustomObject>
    <description>An iteration of the K-Mean algorithm in the Clustering Run</description>
    <fields>
        <fullName>Centroid_Matrix__c</fullName>
        <description>The Matrix of our centroids.</description>
        <label>Centroid Matrix</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Clustering_Run__c</fullName>
        <description>The clustering run that this iteration of the algorithm belongs to.</description>
        <label>Clustering Run</label>
        <referenceTo>Clustering_Run__c</referenceTo>
        <relationshipLabel>Iterations</relationshipLabel>
        <relationshipName>Iterations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Sequence of the Iteration</description>
        <label>Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Iteration</label>
    <nameField>
        <label>Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iterations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KMeansPlaybackControllerTest.cls
/**
  * @author Paul Battisson
  * @description Test class for the KMeansPlaybackController.
  */
@isTest
private class KMeansPlaybackControllerTest {

	private static List<Id> createAccounts(Integer num) {
		List<Account> accounts = new List<Account>();
		for(Integer i = 1; i <= num; i++) {
			Account acc = new Account();
			acc.Name = 'test ' + i;
			acc.json__c = '[' + i*Math.random()*10 + ',' + i*Math.random()*10 + ']';
			accounts.add(acc);
		}

		insert accounts;
		List<Id> accountIds = new List<Id>();
		for(Integer j = 0; j < num; j++) {
			accountIds.add(accounts[j].Id);
		}

		return accountIds;
	}

	private static Clustering_Run__c createRun(List<Id> accountIds) {
		Clustering_Run__c run = new Clustering_Run__c();
		run.Initial_Number_of_Clusters__c = 1;
		run.Dimensions__c = 2;
		run.Max_Value__c = 10;
		insert run;

		Attachment attach = new Attachment();
		attach.Name = 'JSON';
		attach.ParentId = run.Id;
		attach.Body = Blob.valueOf(JSON.serialize(accountIds));
		insert attach;

		return run;
	}

	private static Iteration__c createIteration(Id runId, List<Id> assignIds) {
		
		Iteration__c iteration = new Iteration__c();
		iteration.Clustering_Run__c = runId;
		iteration.Sequence__c = 1;
		iteration.Centroid_Matrix__c = JSON.serialize(new Matrix('[[1,1],[2,2]]'));

		insert iteration;

		Attachment attach = new Attachment();
		attach.Name = 'JSON';
		attach.ParentId = iteration.Id;
		attach.Body = Blob.valueOf(JSON.serialize(new List<List<Id>>{assignIds}));
		insert attach;

		return iteration;
	}

	@isTest 
	private static void testRetrieveIterationData() {
		List<Id> accIds = createAccounts(2);
		Clustering_Run__c run = createRun(accIds);
		Iteration__c iteration = createIteration(run.Id, accIds);

		ApexPages.StandardController stdController = new ApexPages.StandardController(run);
		KMeansPlaybackController controller = new KMeansPlaybackController(stdController);
		System.assertnotEquals(null, controller.initialData);
	}

}