src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>json__c</fullName>
        <label>json</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/Clustering_Run__c.object
<CustomObject>
    <description>This object represents a run of the K-Means clustering algorithm with a series of associated iteration records.</description>
    <fields>
        <fullName>Dimensions__c</fullName>
        <label>Dimensions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initial_Number_of_Clusters__c</fullName>
        <description>The number of clusters that we initially want to work with - note that at the end of our algorithm this may have reduced to a smaller number.</description>
        <label>Number of Clusters</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Value__c</fullName>
        <label>Max Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Clustering Run</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>Clustering Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clustering Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VectorizationBatchTest.cls
@isTest
private class VectorizationBatchTest {

	private static Account createAccount() {
		List<Account> accounts = new List<Account>();
		
		Account acc = new Account();
		acc.Name = 'test Acc';
		acc.ShippingLatitude = 10.0;
		acc.ShippingLongitude = 20.0;

		insert acc;
		
		return acc;
	}

	private static Clustering_Run__c createRun(List<Id> accountIds) {
		Clustering_Run__c run = new Clustering_Run__c();
		run.Initial_Number_of_Clusters__c = 1;
		run.Dimensions__c = 2;
		run.Max_Value__c = 10;
		insert run;

		Attachment attach = new Attachment();
		attach.Name = 'JSON';
		attach.ParentId = run.Id;
		attach.Body = Blob.valueOf(JSON.serialize(accountIds));
		insert attach;

		return run;
	}
	
	@isTest
	static void TestVectorizeAccount() {
		Account acc = createAccount();
		Clustering_Run__c run = createRun(new List<Id>{acc.Id});

		String query = 'Select Id, json__c, ShippingLatitude, ShippingLongitude From Account';
		List<String> fields = new List<String>{'ShippingLatitude', 'ShippingLongitude'};

		Test.startTest();

		Database.executeBatch(new VectorizationBatch(query, run.Id, fields),1);

		Test.stopTest();

		Account updatedAcc = [SELECT Id, json__c FROM Account WHERE Id = :acc.Id];

		System.assertEquals('[10.0,20.0]', updatedAcc.json__c, updatedAcc.json__c);
	}
	
}