src/objects/Clustering_Run__c.object
<CustomObject>
    <description>This object represents a run of the K-Means clustering algorithm with a series of associated iteration records.</description>
    <fields>
        <fullName>Dimensions__c</fullName>
        <label>Dimensions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ids_for_Clustering__c</fullName>
        <description>This field is a hidden field that details that Ids of the records that were used in the clustering algorithm.</description>
        <label>Ids for Clustering</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initial_Number_of_Clusters__c</fullName>
        <description>The number of clusters that we initially want to work with - note that at the end of our algorithm this may have reduced to a smaller number.</description>
        <label>Number of Clusters</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Value__c</fullName>
        <label>Max Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Clustering Run</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>Clustering Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clustering Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Iteration__c.object
<CustomObject>
    <description>An iteration of the K-Mean algorithm in the Clustering Run</description>
    <fields>
        <fullName>Centroid_Matrix__c</fullName>
        <description>The Matrix of our centroids.</description>
        <label>Centroid Matrix</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Clustering_Run__c</fullName>
        <description>The clustering run that this iteration of the algorithm belongs to.</description>
        <label>Clustering Run</label>
        <referenceTo>Clustering_Run__c</referenceTo>
        <relationshipLabel>Iterations</relationshipLabel>
        <relationshipName>Iterations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Sequence of the Iteration</description>
        <label>Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Iteration</label>
    <nameField>
        <label>Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iterations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KMeans.cls
/**
  * @author Paul Battisson, Jennfier Wyher
  *	@description This class has the single static method "runClustering" which should be used as an entry point 
  *				 to initialize a new clustering run on some data set.
  **/
public with sharing class KMeans {

	//Static method to initialize a clustering run for a given record set
	public static Clustering_Run__c createClustering(Set<Id> ids, Integer numClusters, Integer dimensions, Double maxValue) {
		
		Clustering_Run__c run = new Clustering_Run__c();
		//run.Ids_for_Clustering__c = JSON.serialize(ids);
		run.Initial_Number_of_Clusters__c = numClusters;
		run.Dimensions__c = dimensions;
		run.Max_Value__c = maxValue;

		insert run;
		Attachment attach = new Attachment();
		attach.Name = 'JSON';
		attach.ParentId = run.Id;
		attach.Body = Blob.valueOf(JSON.serialize(ids));
		insert attach;
		return run;
	}

	public static Iteration__c initiateClustering(Clustering_Run__c cRun) {
		Iteration__c iteration = new Iteration__c();
		iteration.Clustering_Run__c = cRun.Id;

		Double maxValue = cRun.Max_Value__c;
		Integer dimensions = Integer.valueOf(cRun.Dimensions__c);
		
		Matrix initialCentroids = new Matrix(0, dimensions);

		// Random assignment of the initial centroid
		for(Integer i = 0, j = Integer.valueOf(cRun.Initial_Number_of_Clusters__c); i < j; i++) {
			List<Double> centroid = new List<Double>();
			for(Integer x = 0, y = dimensions; x < y; x++) {
				centroid.add(Math.random()*maxValue);
			}
			initialCentroids.addRow(centroid);
		}

		iteration.Sequence__c = 1;
		iteration.Centroid_Matrix__c = JSON.serialize(initialCentroids);
		insert iteration;

		return iteration;
	}

	public static void kickoffClustering (Iteration__c iteration) {
		Id iterationId = iteration.Id;
		KMeansIteration kmIteration = new KMeansIteration(iterationId);
		Database.executeBatch(kmIteration, 50);		
	}
}