src/objects/Clustering_Run__c.object
<CustomObject>
    <description>This object represents a run of the K-Means clustering algorithm with a series of associated iteration records.</description>
    <fields>
        <fullName>Dimensions__c</fullName>
        <label>Dimensions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ids_for_Clustering__c</fullName>
        <description>This field is a hidden field that details that Ids of the records that were used in the clustering algorithm.</description>
        <label>Ids for Clustering</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initial_Number_of_Clusters__c</fullName>
        <description>The number of clusters that we initially want to work with - note that at the end of our algorithm this may have reduced to a smaller number.</description>
        <label>Number of Clusters</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Value__c</fullName>
        <label>Max Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Clustering Run</label>
    <nameField>
        <displayFormat>CR-{000}</displayFormat>
        <label>Clustering Run</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clustering Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Iteration__c.object
<CustomObject>
    <description>An iteration of the K-Mean algorithm in the Clustering Run</description>
    <fields>
        <fullName>Clustering_Run__c</fullName>
        <description>The clustering run that this iteration of the algorithm belongs to.</description>
        <label>Clustering Run</label>
        <referenceTo>Clustering_Run__c</referenceTo>
        <relationshipLabel>Iterations</relationshipLabel>
        <relationshipName>Iterations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Iteration</label>
    <nameField>
        <label>Iteration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iterations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VectorizationBatch.cls
global class VectorizationBatch implements Database.Batchable<sObject> {
	
	private String query;
	private Clustering_Run__c run;
	private List<String> fieldNames;
	
	global VectorizationBatch(String qryString, Id clusterId, List<String> fields) {
		run = [SELECT Max_Value__c, Dimensions__c, Ids_for_Clustering__c, Initial_Number_of_Clusters__c FROM Clustering_Run__c where Id = :clusterId];
		query = qryString;
		fieldNames = fields;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		Attachment attach = [SELECT Body FROM Attachment WHERE Name = 'JSON' and ParentId = :run.Id];
		Set<Id> ids = (Set<Id>)JSON.deserialize(((Blob)attach.Body).toString(), Set<Id>.class);
		//Set<Id> ids = (Set<Id>)JSON.deserialize(run.Ids_for_Clustering__c, Set<Id>.class);
		return Database.getQueryLocator(query + ' WHERE Id in :ids');
	}

  global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<SObject> jsonRecords = new List<SObject>();
		for(Integer i = 0, j = scope.size(); i < j; i++) {
			jsonRecords.add(vectorise(scope[i]));
		}
		update jsonRecords;
	}
	
	// transform the data and serialize into the json__c field.
	private SObject vectorise(SObject rec) {

		List<Double> vector = new List<Double>();
		Double value;
		for (String f: fieldNames) {
			value = (Double)rec.get(f);
			vector.add(value);
		}
		String s = JSON.serialize(vector);
		rec.put('json__c',s);
		return rec;
	}

	global void finish(Database.BatchableContext BC) {
		Iteration__c iteration = KMeans.initiateClustering(run);	
		KMeans.kickoffClustering(iteration);
	}
	
}